open3d<=0.9 requires python 3.7
fixes:
ERROR: Could not find a version that satisfies the requirement open3d<=0.9 (from versions: 0.10.0.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.13.0)
ERROR: No matching distribution found for open3d<=0.9