Use older open3d version to fix known glibc issue
fix error message:
OSError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ../envs/syconn2/lib/python3.8/site-packages/open3d/libc++abi.so.1)